jenkins:
  systemMessage: "Jenkins Configured using Code"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${adminpw:-PAssw0rd}

  authorizationStrategy:
    globalMatrix:
      Permissions:
        - "Overall/Administer:authenticated"

  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true    

unclassified:
  location:
    adminAddress: "jenkins@example.com"
    url: "http://jenkins.example.com/"

tool:
  git:
    installations:
      - name: Default
        home: "git"